In [1]:
import numpy as np

In [2]:
# Input Array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
#Output
y=np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [10]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [6]:
inputNeurons = X.shape[1]
hiddenNeurons = 3
outputNeurons = 1

wh = np.random.random(size=(inputNeurons,hiddenNeurons))
bh = np.random.random(size=(1,hiddenNeurons))
wout = np.random.random(size=(hiddenNeurons,outputNeurons))
bout = np.random.random(size=(1,outputNeurons))

In [7]:
wh

array([[0.82582113, 0.49425071, 0.2141711 ],
       [0.34469527, 0.08723362, 0.55839551],
       [0.40243086, 0.4203385 , 0.82716574],
       [0.70985506, 0.42937575, 0.85294841]])

In [8]:
wout

array([[0.45001451],
       [0.52372072],
       [0.30212984]])

In [9]:
epochs = 15000
learningRate = 0.01

In [12]:
for i in range(epochs):
#     Feedforward
    hiddenX = X.dot(wh) + bh
    hiddenLayer = sigmoid(hiddenX)
    outputX = hiddenLayer.dot(wout) + bout
    output = sigmoid(outputX)
    
#     Backpropagation
    E = y - output
    slopeOutput = derivativeSigmoid(output)
    slopeHidden = derivativeSigmoid(hiddenLayer)
    
    deltaOutput = slopeOutput * E
    errorHiddenLayer = deltaOutput.dot(wout.T)
    deltaHiddenLayer = slopeHidden * errorHiddenLayer
    
    wout += hiddenLayer.T.dot(deltaOutput) * learningRate
    bout += np.sum(deltaOutput, axis=0, keepdims=True)
    wh += X.T.dot(deltaHiddenLayer) * learningRate
    bh += np.sum(deltaHiddenLayer, axis=0, keepdims=True)

In [13]:
output

array([[0.9488932 ],
       [0.95114946],
       [0.07190709]])

In [14]:
y

array([[1],
       [1],
       [0]])

In [15]:
E

array([[ 0.0511068 ],
       [ 0.04885054],
       [-0.07190709]])