In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('diabetes.csv')

In [3]:
dataset.shape

(768, 9)

In [5]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
X = dataset.iloc[:,0:-1].values

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y = dataset.iloc[:,-1].values

In [9]:
y[:5]

array([1, 0, 1, 0, 1], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [11]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [12]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [13]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [14]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [15]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [16]:
inputNeurons = x_train.shape[1]
hiddenNeurons = 8
outputNeurons = 1

wh = np.random.random(size=(inputNeurons,hiddenNeurons))
bh = np.random.random(size=(1,hiddenNeurons))
wout = np.random.random(size=(hiddenNeurons,outputNeurons))
bout = np.random.random(size=(1,outputNeurons))

In [17]:
x_train.shape

(614, 8)

In [18]:
wh.shape

(8, 8)

In [19]:
wout.shape

(8, 1)

In [56]:
epochs = 15000
learningRate = 0.01

for i in range(epochs):
#     Feedforward
    hiddenX = x_train.dot(wh) + bh
    hiddenLayer = sigmoid(hiddenX)
    outputX = hiddenLayer.dot(wout) + bout
    output = sigmoid(outputX)
    
#     Backpropagation
    E = y_train.reshape(y_train.shape[0],1) - output
#     E = y_train - output
    slopeOutput = derivativeSigmoid(output)
    slopeHidden = derivativeSigmoid(hiddenLayer)
    
    deltaOutput = slopeOutput * E
    errorHiddenLayer = deltaOutput.dot(wout.T)
    deltaHiddenLayer = slopeHidden * errorHiddenLayer
    
    wout += hiddenLayer.T.dot(deltaOutput) * learningRate
    bout += np.sum(deltaOutput, axis=0, keepdims=True)
    wh += x_train.T.dot(deltaHiddenLayer) * learningRate
    bh += np.sum(deltaHiddenLayer, axis=0, keepdims=True)

In [21]:
hiddenX = x_train.dot(wh) + bh

In [23]:
x_train.shape

(614, 8)

In [24]:
wh.shape

(8, 8)

In [25]:
hiddenX.shape

(614, 8)

In [26]:
hiddenLayer = sigmoid(hiddenX)

In [27]:
hiddenLayer.shape

(614, 8)

In [30]:
outputX = hiddenLayer.dot(wout) + bout
output = sigmoid(outputX)

In [32]:
output.shape

(614, 1)

In [43]:
E = y_train.reshape(614,1) - output

In [44]:
E.shape

(614, 1)

In [45]:
y_train.shape

(614,)

In [46]:
output.shape

(614, 1)

In [47]:
slopeOutput = derivativeSigmoid(output)
slopeHidden = derivativeSigmoid(hiddenLayer)

In [48]:
slopeOutput.shape

(614, 1)

In [49]:
E.shape

(614, 1)

In [50]:
deltaOutput = slopeOutput * E

In [51]:
deltaOutput.shape

(614, 1)

In [52]:
wout.shape

(8, 1)

In [53]:
errorHiddenLayer = deltaOutput.dot(wout.T)

In [54]:
errorHiddenLayer.shape

(614, 8)