In [1]:
import tensorflow as tf
import numpy as np

In [3]:
x = tf.constant('hello')

In [4]:
y = "world"

In [5]:
x+y

<tf.Tensor 'add:0' shape=() dtype=string>

In [6]:
x = tf.constant(6)
y = tf.constant(10)

In [7]:
z = x + y

In [8]:
z

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [9]:
sess = tf.Session()
sess.run(z)

16

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.linspace(2,20,30,retstep=True)

(array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
         5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
         8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
        11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
        14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
        17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ]),
 0.6206896551724138)

In [13]:
ones = tf.ones((3,3))

In [14]:
zeros = tf.zeros((3,3))

In [19]:
arr_1 = tf.linspace(2.0,20.0,20)

In [21]:
matrix = [ones,zeros,arr_1]
with tf.Session() as sess:
    for item in matrix:
        print(sess.run(item))
        print()

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[ 2.         2.9473684  3.8947368  4.8421054  5.7894735  6.736842
  7.684211   8.631578   9.578947  10.526316  11.473684  12.421053
 13.368422  14.31579   15.263158  16.210526  17.157894  18.105263
 19.052631  20.       ]



In [22]:
data_1 = tf.random_normal((4,4))
data_2 = tf.random_normal((4,4))

In [23]:
add = tf.add(data_1,data_2)
mul = tf.matmul(data_1,data_2)

In [24]:
with tf.Session() as sess:
    print(sess.run(add))
    print(sess.run(mul))

[[ 0.6359876   0.7614708   1.7506181  -2.3730135 ]
 [-0.6575277  -1.5243409   1.441887   -0.47140187]
 [ 0.16558293  2.9830294   1.2573869   0.9845091 ]
 [-0.02375516 -0.6507275  -0.2940886   2.467098  ]]
[[ 0.6723713  -1.6194109  -4.5477915   0.7296296 ]
 [-1.1597964  -2.9476397  -6.558132    2.2016551 ]
 [ 2.1320934   1.232758    2.1204581   0.12491331]
 [ 0.65988207  0.30928355 -1.1596017  -0.3467767 ]]


In [25]:
X = np.random.random((4,4))
y = np.random.random((4,4))

In [28]:
placeholder_1 = tf.placeholder(tf.float32, shape=(4,4))
placeholder_2 = tf.placeholder(tf.float32, shape=(4,4))

In [26]:
add = tf.add(placeholder_1, placeholder_2)
mul = tf.matmul(placeholder_1, placeholder_2)

In [30]:
with tf.Session() as sess:
    print(sess.run(add,feed_dict={placeholder_1:X,placeholder_2:y}))
    print(sess.run(mul,feed_dict={placeholder_1:X,placeholder_2:y}))

[[1.60536536 0.77531593 0.9134929  0.8868531 ]
 [1.8028215  0.69550772 1.92844411 0.93326635]
 [1.71205651 1.09163187 0.94596366 0.86446703]
 [1.58727953 1.42735435 0.26408959 1.334064  ]]
[[1.76080001 0.86937531 0.95420152 1.11495533]
 [1.93484281 0.7361801  0.83711528 0.8576885 ]
 [2.7998668  1.50373764 1.36984937 1.78915986]
 [1.76615478 0.97243827 0.94631106 1.2698677 ]]


In [31]:
a = tf.Variable(2)
b = tf.Variable(4)
c = a + b

Instructions for updating:
Colocations handled automatically by placer.


In [32]:
c

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [33]:
init = tf.global_variables_initializer()

In [34]:
sess = tf.InteractiveSession()
init.run()
sess.run(c)

6